#!/bin/bash
now=`date +'%m%d%y'`
now2=`date +'%B %d, %Y'`
day=`date +'%d'`
month=`date +'%m'`
year=`date +'%Y'`

mkdir "$now"
echo "## $now2" > "$now/README.md"
echo "- [$month.$day.$year](https://github.com/myoiwritescode/TIL/tree/master/$now)" >> README.md
echo "$now2 added"
